language: csharp
script:
  - xbuild /p:Configuration=Debug SampleTest.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore SampleTest.sln
after_script:
  - nunit-console SampleTest.Test/bin/Debug/SampleTest.Test.dll